# Generated by Django 3.1.7 on 2021-02-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(help_text='Enter Employee ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(default='Missing', max_length=100, null=True)),
                ('section', models.CharField(default='Missing', max_length=100, null=True)),
                ('position', models.CharField(default='Missing', max_length=100, null=True)),
                ('grade', models.CharField(default='-', max_length=10, null=True)),
                ('is_expatriate', models.BooleanField(default=False)),
                ('is_exclude', models.BooleanField(default=False)),
                ('join_date', models.DateField(null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('resign_flag', models.CharField(choices=[('A', 'A'), ('P', 'P'), ('R', 'R'), ('-', '-')], max_length=1, null=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
